name: Herobrine
main: AwesomeMan2812.plugins.herobrine.main
version: 1.0
authors: [AwesomeMan2812]
depend: [WorldEdit]
commands:
   hb:
      description: Main Herobrine Command
      usage: /<command> [action]
      permission: hb.default
      permission-message: You don't have permission to use this command!
permissions:
    hb.*:
        description: Gives access to all Herobrine.
        default: op
        children:
            herobrine.command.setlobby: true
            herobrine.command.setmlobby: true
            herobrine.command.createarena: true
            herobrine.command.setspawn: true
            herobrine.command.deletearena: true
            herobrine.command.start: true
            herobrine.command.stop: true
            herobrine.command.join: true
            herobrine.command.leave: true
    hb.default:
        description: Gives access to User SCB Commmands.
        default: true
        children:
            scb.signs.use: true
            scb.command.selclass: true
            scb.classes.default: true
    hb.mod:
        description: Gives access to Moderator SCB Commands.
        default: op
        children:
            scb.command.join: true
            scb.command.leave: true
            scb.signs.use: true
            scb.command.start: true
            scb.command.disable: true
            scb.command.enable: true
            scb.classes.default: true
