name: Herobrine
main: AwesomeMan2812.main.herobrine
version: 3.0
authors: [AwesomeMan2812]
softdepend: [WorldEdit]
commands:
   hb:
      description: Main Herobrine Command
      usage: /<command> [action]
      permission: hb.main
      permission-message: You don't have permission to use this command!
permissions:
    hb.*:
        description: Gives access to all Herobrine.
        default: op
        children:
            herobrine.command.create: true
            herobrine.command.delete: true
            hb.command.disable: true
            hb.command.enable: true
            hb.command.join: true
            hb.command.leave: true
            hb.command.setglobby: true
            hb.command.setspawn: true
            hb.command.start: true
            hb.signs.use: true
            hb.command.selclass: true
    hb.default:
        description: Gives access to User SCB Commmands.
        default: true
        children:
            scb.signs.use: true
            scb.command.selclass: true
            scb.classes.default: true
    hb.mod:
        description: Gives access to Moderator SCB Commands.
        default: op
        children:
            scb.command.join: true
            scb.command.leave: true
            scb.signs.use: true
            scb.command.start: true
            scb.command.disable: true
            scb.command.enable: true
            scb.classes.default: true
