name: Herobrine
main: AwesomeMan2812.plugins.herobrine.main
version: 1.0
authors: [AwesomeMan2812]
depend: [WorldEdit]
commands:
   hb:
      description: Main Herobrine Command, type /hb help for more!
      usage: /<command> [action]
      permission: hb.default
      permission-message: You don't have permission to use this command!
permissions:
    hb.*:
        description: Gives access to all Herobrine Commands.
        default: op
        children:
            herobrine.command.setlobby: true
            herobrine.command.setglobby: true
            herobrine.command.createarena: true
            herobrine.command.setspawn: true
            herobrine.command.deletearena: true
            herobrine.command.start: true
            herobrine.command.stop: true
            herobrine.command.join: true
            herobrine.command.leave: true
    hb.default:
        description: Gives access to User Herobrine Commmands.
        default: true
        children:
            herobrine.signs.use: true
            herobrine.command.join: true
            herobrine.command.leave: true
    hb.mod:
        description: Gives access to Moderator Herobrine Commands.
        default: op
        children:
            herobrine.command.start: true
            herobrine.command.disable: true
            herobrine.command.enable: true
